/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        StandardCalculator calc = new StandardCalculator();
        calc.add(1,1);
        System.out.println("Addition: "+calc.getResult());
        calc.clearResult();
        calc.printResult();
        calc.multiply(3,4);
        System.out.println("Multiplication: "+calc.getResult());
        calc.clearResult();
        calc.printResult();

    }
}
